CREATE TABLE IF NOT EXISTS RAW.RBI_PAYMENT_TRANSACTIONS (
    REPORT_PERIOD DATE,
    METRIC_CODE VARCHAR,
    METRIC_NAME VARCHAR,
    VOLUME_LAKH FLOAT,
    VALUE_CRORE FLOAT
);

CREATE TABLE IF NOT EXISTS RAW.RBI_PAYMENT_CHANNELS (
    REPORT_PERIOD DATE,
    METRIC_CODE VARCHAR,
    METRIC_NAME VARCHAR,
    VOLUME_LAKH FLOAT,
    VALUE_CRORE FLOAT
);

CREATE TABLE IF NOT EXISTS RAW.RBI_PAYMENT_INFRASTRUCTURE (
    REPORT_PERIOD VARCHAR,
    METRIC_CODE VARCHAR,
    METRIC_NAME VARCHAR,
    METRIC_VALUE FLOAT
);

CREATE TABLE IF NOT EXISTS RAW.RBI_PAYMENT_FRAUDS (
    REPORT_PERIOD DATE,
    FRAUD_VOLUME_LAKH FLOAT,
    FRAUD_VALUE_CRORE FLOAT
);